apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Servidor Let's Encrypt de produção
    server: https://acme-v02.api.letsencrypt.org/directory
    
    # Email para notificações (SUBSTITUA pelo seu email)
    email: gustavo.costa@extreme.digital
    
    # Secret para armazenar a chave privada da conta ACME
    privateKeySecretRef:
      name: letsencrypt-prod
    
    # Solver HTTP-01 usando nginx-ingress
    solvers:
    - http01:
        ingress:
          class: nginx